import type { TeamMember } from "../types.ts";

export const team: TeamMember[] = [
  { name: "Paweł Czapliński", role: "Prezes Zarządu Fundacji Aktywności Zawodowej" },
  { name: "Hania Czaplińska", role: "Wiceprezes Fundacji Aktywności Zawodowej" },
  { name: "Michał Czapiewski", role: "Wiceprezes Fundacji Aktywności Zawodowej" },
  { name: "Marek Wikiera", role: "Członek Rady Fundacji Aktywności Zawodowej" },
  { name: "Karolina Mikołajewska", role: "Członkini Rady Fundacji Aktywności Zawodowej" },
  { name: "Darek Witt", role: "Członek Rady Fundacji Aktywności Zawodowej" },
  { name: "Olga Siedorow", role: "Specjalistka ds. księgowości i kadr" },
  { name: "Marta Sieńko", role: "Specjalistka ds. szkoleń" },
  { name: "Aneta Ksiądz", role: "Psycholog" },
  { name: "Anna Szczęśniak", role: "Doradczyni zawodowa" },
  { name: "Kinga Nowakowska", role: "Mentorka" },
  { name: "Angelika Bendowska", role: "Specjalistka ds. szkoleń" },
  { name: "Julia Weber", role: "Pośredniczka pracy" },
  { name: "Michał Urban", role: "Pośrednik pracy" },
  { name: "Tomek Borowski", role: "Doradca zawodowy" },
  { name: "Bartosz Ziarnik", role: "Prawnik" },
  { name: "Justyna Piaskowska", role: "Mentorka" },
  { name: "Małgorzata Lipińska-Dawid", role: "Psycholożka" },
  { name: "Ida Jarzyńska", role: "Doradczyni zawodowa" },
  { name: "Marek Pieńkowski", role: "Koordynator projektu" },
  { name: "Anna Dąbek", role: "Pośredniczka pracy" },
  { name: "Łukasz Tebich", role: "Psycholog" },
  { name: "Aleksandra Wójcik", role: "Pośredniczka pracy" },
  { name: "Agnieszka Lorek", role: "Doradczyni zawodowa" },
  { name: "Łucja Penk", role: "Specjalistka ds. komunikacji" },
  { name: "Anna Żłobecka", role: "Pośredniczka pracy" },
  { name: "Marcelina Hernik", role: "Specjalistka ds. dostępności" },
  { name: "Natalia Gozłowska", role: "Asystentka Zarządu" },
  { name: "Ewa Wiśniewska", role: "Doradca zawodowy" },
  { name: "Michał Hajdyła", role: "Psycholog" },
  { name: "Hanna Musiał", role: "Specjalistka ds. szkoleń" },
  { name: "Michalina Bernatek", role: "Doradczyni zawodowa" },
  { name: "Dorota Ulicyn", role: "Pośredniczka pracy" },
  { name: "Oskar Kowalczyk", role: "Psycholog" },
];
